#!/bin/bash

dist=$(echo $1 | tr "_" "-")

html=$(curl https://pypi.python.org/simple/$dist/ 2> /dev/null)
html=$(echo $html | sed -E 's/.*h1>//')
html=$(echo $html | sed -E 's/<[^>]*>//g')

function process_source
{
    echo "$1" | sed -e "s/.*-\(.*\)\.tar\.gz/\1/g"
}

function parse_wheel_filename
{
    # $2 = 1 -> distribution
    # $2 = 2 -> version
    # $2 = 3 -> build tag
    # $2 = 4 -> python tag
    # $2 = 5 -> abi tag
    # $2 = 6 -> platform tag
    echo "$1" | sed -e "s/^\(.*\)-\(.*\)\(-\d.*\)\?-\(.*\)-\(.*\)-\(.*\)\.whl$/\\$2/" | tr "-" "_"
}

function process_wheel
{
    str="distribution=$(parse_wheel_filename $1 1);"
    str="${str}version=$(parse_wheel_filename $1 2);"
    str="${str}build=$(parse_wheel_filename $1 3);"
    str="${str}python=$(parse_wheel_filename $1 4);"
    str="${str}abi=$(parse_wheel_filename $1 5);"
    str="${str}platform=$(parse_wheel_filename $1 6);"
    echo $str
}

function src_latest_version
{
    echo "$1" | tr " " "\n" | sort --version-sort | tail -1
}

function wheel_latest_version
{
    wheels=$(echo "$1" | tr " " "\n")
    versions=""
    for w in $wheels
    do
        v=$(echo $w | sed -e "s/^.*version=\([^;]*\);.*$/\1/")
        versions="$versions $v"
    done
    echo "$versions" | tr " " "\n" | sort --version-sort | tail -1
}

wheel_data=""
src_versions=""

for fn in $html
do
    if [[ $fn =~ ^.*\.whl$ ]]
    then
        wheel_data="$(process_wheel $fn) $wheel_data"
    elif [[ $fn =~ ^.*\.tar\.gz$ ]]
    then
        src_versions="$(process_source $fn) $src_versions"
    fi
done

if ! [ -z "$wheel_data" ];
then
    wheel_data="${wheel_data::-1}"
fi

if ! [ -z "$src_versions" ];
then
    src_versions="${src_versions::-1}"
fi

src_ver=$(src_latest_version "$src_versions")
echo "Latest source version: $src_ver"

wheel_ver=$(wheel_latest_version "$wheel_data")
echo "Latest wheel version: $wheel_ver"
